services:
    shopware_search.anhchor.listener:
        class: Shopware\Devdocs\AnchorListener
        tags:
            - { name: kernel.event_subscriber }

    webuni.commonmark.tablextension:
        class: Webuni\CommonMark\TableExtension\TableExtension
        tags:
            - { name: sculpin_commonmark.extension }

    shopware_devdocs.twig_extension:
        class: Shopware\Devdocs\TwigExtension
        arguments:
            - %kernel.environment%
        tags:
            - { name: twig.extension }
